// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
    diablo4Sidebar: [
        'diablo4/index',
        {
            type: 'category',
            label: '시즌 11',
            items: [
                'diablo4/season11/01',
                'diablo4/season11/02',
                'diablo4/season11/03',
                'diablo4/season11/04',
                'diablo4/season11/05',

            ],
        },
        {
            type: 'category',
            label: '시즌 12',
            items: [
                'diablo4/season12/index',
            ],
        }
    ],
};

export default sidebars;
